import type { NextPage } from 'next'
import { useDispatch, useSelector } from 'react-redux'
import { addNumber, setFormData, postFormData } from '../store/actionsCreators/counter'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useTypedSelector } from '../hooks/useTypeSelector'

const Home: NextPage = () => {
  const dispatch = useDispatch()
  
  const {
    number,
    formData
  } = useTypedSelector(state => state.counter)

  const buttonAdd = () => {
    dispatch(addNumber(number))
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Learn next ts redux</h1>
        <p>Counter: {number}</p>
        <label>Name:
          <input 
            onChange={(e) => {
              dispatch(setFormData({
                ...formData,
                name: e.target.value
              }))
            }
            }
          />
        </label>

        <label>Umur:
          <input 
            type="number"
            onChange={(e) => {
              dispatch(setFormData({
                ...formData,
                age:Number( e.target.value)
              }))
            }}
          />
        </label>
        <button
          onClick={() => dispatch(postFormData(formData))}
        >Add</button>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
